config/routes.rb
Rails.application.routes.draw do
  namespace :backend, path: "admin" do
    root 'pages#home'

    get 'sign_in', to: 'sessions#new', as: 'sign_in'
    post 'sign_in', to: 'sessions#create'
    delete 'sign_out', to: 'sessions#destroy', as: 'sign_out'

    resources :users
    resources :categories, except: :show
    resources :custom_windows
    resources :products do
      member do
        get :set_cover
      end

      resources :options do
        collection do
          put :update_all
        end
      end
      resources :variants
      resources :product_images
    end

    resources :pictures, only: :create
  end

  namespace :frontend, path: "shop" do
    root 'pages#home'

    get 'sign_in', to: 'sessions#new', as: 'sign_in'
    post 'sign_in', to: 'sessions#create'
    delete 'sign_out', to: 'sessions#destroy', as: 'sign_out'

    get 'settings', to: 'customers#edit', as: :settings

    resources :search, only: :index

    get 'p/:slug', to: 'products#show', as: :display_spu
    resources :products, only: [:index], param: :slug do
      # get '/content', to: 'products#content'
      # get '/basic', to: 'products#basic'

      collection do
        get 'new_arrival'
        get 'hot_sales'
      end
    end

    resources :customers
    resources :addresses

    resources :variants do
      collection do
        get  :get_selected
      end
    end

    resource :cart, only: [:show] do
      post 'add_to_cart', to: 'carts#add', as: :add_to
      post 'remove_from_cart/:variant_id', to: 'carts#remove', as: :remove_from
      post 'change_qty/:variant_id', to: 'carts#change_qty', as: :change_qty_in
    end

    get 'my_wish_list', to: 'wish_lists#my', as: :my_wish_list
    post '/wish/:product_id', to: 'wish_lists#add', as: :add_to_wish_list
    delete '/wish/:product_id', to: 'wish_lists#remove', as: :remove_from_wish_list

    resources :categories, only: :show, param: :slug do
      get 'tags/:tag_id', action: :tag, on: :member, as: :tag
    end
    resources :tags, only: :show
  end

  root 'frontend/pages#home'
end

app/models/product.rb
class Product < ApplicationRecord
  include ProductsSearchable

  belongs_to :category
  has_many :variants, dependent: :destroy
  has_many :options, dependent: :destroy
  has_many :product_images, dependent: :destroy
  has_many :taggings, dependent: :destroy
  has_many :tags, through: :taggings, dependent: :destroy

  # accepts_nested_attributes_for :options

  validates_length_of :options, maximum: 3
  validates :title, presence: true
  validates :price, presence: true

  before_create :init_slug

  delegate :name, to: :category, prefix: true
  scope :not_deleted, -> { where(deleted_at: nil) }
  scope :hot_sales,
        -> { where(deleted_at: nil, hot_sale: 1).order('created_at DESC') }
  scope :new_arrivals,
        -> { where(deleted_at: nil, new_arrival: 1).order('created_at DESC') }

  SOLD_OUT = 0
  ON_OFFER = 1

  STATUS = {
    SOLD_OUT => '下架',
    ON_OFFER => '在售'
  }

  def tag_list=(names)
    self.tags = names.map do |n|
      Tag.where(name: n.strip).first_or_create!
    end
  end

  def tag_list
    tags.pluck(:name)
  end

  def self.tagged_with(name)
    Tag.find_by!(name: name).products
  end

  def wished_by_count_key
    "wished_by_count:#{id}"
  end

  private

  def init_slug
    loop do
      slug = SecureRandom.urlsafe_base64
      break self.slug = slug unless Product.exists?(slug: slug)
    end
  end
end

# == Schema Information
#
# Table name: products
#
#  id           :integer          not null, primary key
#  title        :string
#  body_html    :text
#  published_at :datetime
#  vendor       :string
#  keywords     :text
#  price        :decimal(8, 2)
#  category_id  :integer
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#  slug         :string
#  deleted_at   :datetime
#  stock_qty    :integer          default(0)
#  status       :integer          default(0)
#  hot_sale     :boolean          default(FALSE)
#  new_arrival  :boolean          default(TRUE)
#  cover        :string
#
# Indexes
#
#  index_products_on_category_id  (category_id)
#  index_products_on_deleted_at   (deleted_at)
#

app/controllers/backend/products_controller.rb
class Backend::ProductsController < Backend::ApplicationController
  before_action :get_product, only: [:show, :edit, :update, :destroy, :set_cover]
  before_action -> { authorize Product }
  def new
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to new_backend_product_option_path(@product), notice: '商品已创建成功' }
      else
        format.html { render :new }
        format.js { render :new }
      end
    end
  end

  def edit
  end

  def update
    if @product.update(product_params)
      redirect_to [:backend, @product]
    else
      render :edit
    end
  end

  def index
    @products = Product.not_deleted
  end

  def destroy
    @product.update(deleted_at: Time.now)
    redirect_to backend_products_path, notice: "#{@product.title} 已被删除"
  end

  def set_cover
    img = @product.product_images.find(params[:product_image_id])
    @product.update_column(:cover, img.img_url(:big))
  end

  private
  def product_params
    params.require(:product)
          .permit(:title, :price, :stock_qty, :status, :vendor, :body_html, :category_id, :new_arrival, :hot_sale, tag_list: [])
  end
end

app/controllers/frontend/addresses_controller.rb
class Frontend::AddressesController < Frontend::ApplicationController
  before_action :current_customer_exists?

  def index
    @addresses = current_customer.addresses
    @address   = Address.new
  end

  def create
    @address = current_customer.addresses.build(address_params)
    if @address.save
      flash[:notice] = '新建成功'
    else
      flash[:notice] = @address.errors.full_messages.join(' 。')
    end
    redirect_to frontend_addresses_url
  end

  def edit
    @addresses = current_customer.addresses
    @address   = current_customer.addresses.find(params[:id])
    render :index
  end

  def update
    @address = current_customer.addresses.find(params[:id])
    if @address.update(address_params)
      flash[:notice] = '已更新成功'
    else
      flash[:notice] = @address.errors.full_messages.join(' 。')
    end
    respond_to do |format|
      format.html { redirect_to frontend_addresses_url }
      format.js
    end
  end

  def destroy
    @address = current_customer.addresses.find(params[:id])
    @address.destroy
    redirect_to frontend_addresses_url
  end

  private

  def address_params
    params.require(:address).permit!
  end
end

app/controllers/frontend/application_controller.rb
class Frontend::ApplicationController < ActionController::Base
  layout "application"
  protect_from_forgery with: :exception
  before_action :detect_device_variant
  before_action :get_top_categories

  private

  def detect_device_variant
    request.variant = :phone if browser.device.mobile? || browser.device.tablet?
  end

  def current_customer
    if customer_id = session[:customer_id]
      @current_customer ||= Customer.find customer_id
    elsif customer_id = cookies.signed[:customer_id]
      customer = Customer.find customer_id
      if customer && customer.remember_token == cookies.signed[:remember_token]
        session[:customer_id] = customer.id
        @current_customer = customer
      end
    end
  end
  helper_method :current_customer

  def current_cart
    @current_cart ||= if current_customer
                        current_customer.cart_items
                      else
                        []
                      end
  end
  helper_method :current_cart

  def current_customer_exists?
    return unless current_customer.present?
    redirect_to frontend_root_path && return
  end

  def get_top_categories
    @categories = Category.get_categories
  end
end

app/controllers/frontend/carts_controller.rb
class Frontend::CartsController < Frontend::ApplicationController
  skip_before_action :get_top_categories, only: [:add, :remove, :change_qty]
  before_action :current_customer_exists?

  def show
    @cart_items = current_customer.cart_items
  end

  def add
    key = current_customer.cart_key
    variant_id = params[:variant_id]
    qty = params[:quantity]
    redis.hincrby key, variant_id, qty if variant_id.present?
  end

  def change_qty
    key = current_customer.cart_key
    variant_id = params[:variant_id]
    @variant = Variant.find variant_id
    qty = params[:quantity]
    redis.hset key, variant_id, qty if variant_id.present?
  end

  def remove
    redis.hdel current_customer.cart_key, params[:variant_id]
  end

  private

  def redis
    Redis.current
  end
end

app/controllers/frontend/categories_controller.rb
class Frontend::CategoriesController < Frontend::ApplicationController
  def show
    @category = Category.find_by(slug: params[:slug])
    @products = @category.products.not_deleted
                         .order('created_at DESC')
                         .page(params[:page]).per(2)

    render 'frontend/products/index'
  end

  def tag
    @tag = Tag.find(params[:tag_id])
    @category = Category.find_by(slug: params[:slug])
    @products = Product.tagged_with(@tag.name).not_deleted
                       .where(category: @category)
                       .order('created_at DESC')
                       .page(params[:page]).per(12)

    render 'frontend/products/index'
  end
end

app/controllers/frontend/customers_controller.rb
class Frontend::CustomersController < Frontend::ApplicationController
  def new
    @customer = Customer.new(customer_params)
  end

  def create
    @customer = Customer.new(customer_params)

    if @customer.save
      session[:customer_id] = @customer.id
      redirect_to root_path
    else
      flash[:notice] = @customer.errors.full_messages.join(' 。')
      redirect_to new_customer_path(customer: { name: customer_params[:name],
                                                email: customer_params[:email] })

    end
  end

  def edit

  end

  def update
    if current_customer && current_customer.authenticate(params[:customer][:old_password])
      if current_customer.update(customer_params)
        flash[:alert] = '密码更新成功, 请牢记, 谢谢.'
      else
        flash[:alert] = '确认密码不一致, 请重新输入.'
      end
    else
      flash[:alert] = '旧密码有误, 请重新输入'
    end
    redirect_to frontend_settings_path
  end

  private

  def customer_params
    params.require(:customer).permit(:email, :password, :password_confirmation, :name) if params[:customer]
  end
end

app/controllers/frontend/pages_controller.rb
class Frontend::PagesController < Frontend::ApplicationController
  def home
    # CustomWindow
    @cw0 = CustomWindow.features[0]
    @cw1 = CustomWindow.features[1]
    @cw2 = CustomWindow.features[2]
    @cw3 = CustomWindow.features[3]
    @cw4 = CustomWindow.features[4]
    @cw5 = CustomWindow.features[5]
    @cw6 = CustomWindow.features[6]
    # products list
    @products = Product.not_deleted.new_arrivals.page(params[:page]).per(12)
  end
end

app/controllers/frontend/products_controller.rb
class Frontend::ProductsController < Frontend::ApplicationController
  def index
    render :index
  end

  def new_arrival
    @products = Product.new_arrivals.page(params[:page]).per(12)
    index
  end

  def hot_sales
    @products = Product.hot_sales.page(params[:page]).per(12)
    index
  end

  def show
    @product = Product.where(slug: params[:slug]).first
    @options = @product.options
    @no_footer           = true
    @no_top_menu         = true
    @no_top_search       = true
    @display_bottom_menu = true
  end

  # def content
  #   @product = Product.where(slug: params[:product_slug]).first
  #   @p_body = @product.body_html
  # end
end

app/controllers/frontend/search_controller.rb
class Frontend::SearchController < Frontend::ApplicationController
  after_action -> { Suggestion.save_word(params[:q]) }, only: [:index]

  def index
    @search = Product.custom_search(params)
    @total  = @search.total_count
    @products = @search.results
  end
end

app/controllers/frontend/sessions_controller.rb
class Frontend::SessionsController < Frontend::ApplicationController
  def new
    if current_customer
      redirect_to frontend_root_path, notice: '已经登录了.'
      return
    end
  end

  def create
    customer = Customer.find_by(email: params[:email])

    if customer && customer.authenticate(params[:password])
      session[:customer_id] = customer.id

      if params[:remember_me].present?
        customer.remember
        cookies.signed[:customer_id] = { value: customer.id, expires: 1.week.from_now }
        cookies.signed[:remember_token] = { value: customer.remember_token, expires: 1.week.from_now }
      end

      redirect_to(params[:prev_url] || frontend_root_path)
    else
      redirect_to frontend_sign_in_path, alert: '邮箱与密码不匹配'
    end
  end

  def destroy
    session.delete(:customer_id)
    cookies.delete(:customer_id)
    cookies.delete(:remember_token)
    redirect_to frontend_root_path, notice: '帐户已登出'
  end
end

app/controllers/frontend/tags_controller.rb
class Frontend::TagsController < Frontend::ApplicationController
  def show
    @tag = Tag.find(params[:id])
    @products = Product.tagged_with(@tag.name).not_deleted
                       .order('created_at DESC')
                       .page(params[:page]).per(12)

    render 'frontend/products/index'
  end
end

app/controllers/frontend/variants_controller.rb
class Frontend::VariantsController < Frontend::ApplicationController

  def add_to_cart
  end

  def get_selected
    vals = params[:opts]
    product = Product.find params[:product_id]
    # options_count = product.options.count
    @variant = product.variants.where(option1: vals[0],
                                      option2: vals[1],
                                      option3: vals[2]).first
  end
end

app/controllers/frontend/wish_lists_controller.rb
class Frontend::WishListsController < Frontend::ApplicationController
  skip_before_action :get_top_categories, only: [:add, :remove]
  before_action :current_customer_exists?

  def my
    @wish_lists = current_customer.wish_lists
  end

  def add
    @product = Product.find(params[:product_id])
    current_customer.wish params[:product_id]
    @current_count = current_customer.wish_list_items_count
  end

  def remove
    @product = Product.find(params[:product_id])
    current_customer.wish params[:product_id]
    @current_count = current_customer.wish_list_items_count
  end
end

app/helpers/backend/products_helper.rb
module Backend::ProductsHelper
end

app/helpers/frontend/addresses_helper.rb
module Frontend::AddressesHelper
end

app/helpers/frontend/customers_helper.rb
module Frontend::CustomersHelper
end

app/helpers/frontend/products_helper.rb
module Frontend::ProductsHelper
end

app/helpers/frontend/search_helper.rb
module Frontend::SearchHelper
end

app/helpers/frontend/tags_helper.rb
module Frontend::TagsHelper
end

app/views/frontend/products/_products_list.html.erb
<div class="ui container">
  <div class="ui grid" id="products_list">
    <div class="three wide column computer only">
      <div class="ui vertical fluid tabular menu" id="left_navs">
        <div class="item">
          <div class="header">新品</div>
        </div>
        <div class="item">
          <div class="header">爆款</div>
        </div>
        <%= render partial: 'frontend/common/left_nav_categories', collection: @categories, as: :category %>
      </div>
    </div>
    <div class="thirteen wide computer sixteen wide mobile column" id="right_products">
      <div class="ui segment clearing">
        <div class="ui basic segment">
          <div class="ui four stackable cards">
            <% @products.each do |product| %>
              <%= link_to frontend_display_spu_path(product.slug), class: 'card' do  %>
                <div class="image">
                  <%= image_tag(product.cover || 'logo.png') %>
                </div>
                <div class="extra content">
                  <div class="header">
                    <%= product.title %>
                    <div class="right floated price">
                      ¥ <%= product.price %>
                    </div>
                  </div>
                </div>
              <% end %>
             <% end %>
          </div>
        </div>
        <%= paginate @products %>
      </div>
    </div>
  </div>

</div>

app/views/frontend/products/_wish_btn.html.erb
<% if current_customer.wished?(@product) %>
  <%= link_to frontend_add_to_wish_list_path(product_id: @product.id), method: :post, remote: true, class: 'ui yellow inverted large button wish_btn' do %>
    <i class="star icon"></i> 已收藏
  <% end %>
<% else %>
  <%= link_to frontend_add_to_wish_list_path(product_id: @product.id), method: :post, remote: true, class: 'ui yellow large button wish_btn' do %>
    <i class="star icon"></i> 收藏了再说
  <% end %>
<% end %>

app/views/frontend/products/index.html+phone.erb
<div id="products-page">
  <h4 class="ui clearing horizontal divider header">
    <%= render_products_list_title %>
  </h4>
  <%= render 'frontend/common/phone/tags_box' %>

  <div class="ui container" id="products-box">
    <div class="ui two cards">
      <% @products.each do |product| %>
        <%= link_to frontend_display_spu_path(product.slug), class: 'blue card' do  %>
          <div class="image">
            <%= image_tag('', data: {original: product.cover || 'logo.png'}, class: 'lazy',) %>
          </div>
          <div class="extra content">
            <div class="header product-title">
              <%= product.title %>
              <div class="right floated price">
                ¥ <%= product.price %>
              </div>
            </div>
          </div>
        <% end %>
      <% end %>
      <div id="mobile-paginator">
        <%= paginate @products %>
      </div>
    </div>
  </div>
</div>

app/views/frontend/products/index.html.erb
<%= render 'frontend/products/products_list' %>

app/views/frontend/products/show.html+phone.erb
<%
  scrubber = Loofah::Scrubber.new do |node|
    node.remove if node.name == 'script'
  end
%>
<div id="product-show">
  <div class="ui pointing secondary menu" style="margin-bottom: 0;">
    <%= link_to request.env['HTTP_REFERER'] || '/', class: 'item' do %>
      <i class="chevron left icon"></i>
    <% end %>
    <a class="active item" data-tab='basic-info-tab'>基本信息</a>
    <a class="item" data-tab='body-content-tab' id="body-content-tab">商品详情</a>
    <a class="item" data-tab='comments-tab' id="comments-tab">评价</a>
  </div>
  <div class="ui active tab" data-tab="basic-info-tab">
    <div class="product-imgs-owl owl-carousel owl-theme">
      <% @product.product_images.each do |img| %>
        <div>
          <%= image_tag img.img_url(:big), style: 'width: 100%' %>
        </div>
      <% end %>
    </div>
    <div class="ui container product-meta" style="margin-top: 10px;">
      <h1 style="color: #5bb5ff; font-weight: normal;font-size: 1.3em">
        <%= @product.title %>
      </h1>
      <p style="color: #5bb5ff; font-size: 1.8em; font-weight: bold;">
        ¥ <%= @product.price %>
      </p>
    </div>
  </div>

  <div data-tab="body-content-tab" class="ui tab" id="body-content">
      <%= sanitize @product.body_html, scrubber: scrubber %>
  </div>
</div>

<script>
  $(document).ready(function() {
    $('#select_variant_form').submit(function () {
      var valid = true;
      $.each($('.option'), function(index, val) {
        if ($(val).find('input:radio:checked').length == 0) {
          $(val).prev().show();
          valid = false;
        } else {
          $(val).prev().hide();
        }
      });
      if (!valid) {return false;}
    });

    $('#select_variant_form input:radio').on('click', function() {
      if ($('.option input:radio:checked').length == $('.option').length) {
        var arr = new Array();
        $(':radio:checked').each(function(){
          arr.push($(this).val());
        });
        $.ajax({
             type: 'GET',
             url: '/shop/variants/get_selected',
             dataType: 'script',
             data: { opts: arr, product_id: <%= @product.id %> }
         });
      }
    });
    $('.ui.menu .item').tab();

    // $.fn.api.settings.api = {
    //     'get product basic'      : '/shop/products/{product_slug}/basic',
    //     'get product body'       : '/shop/products/{product_slug}/content',
    // };

    // $('#body-content-tab').api({
    //     action: 'get product body',
    //     method : 'GET',
    //     dataType: 'html',
    //     stateContext : '#body-content',
    //     urlData: {
    //       product_slug: '<%#= @product.slug %>',
    //     },
    //     onSuccess: function(response) {
    //       // load response content in "youtube_tab_content"
    //       $('#body-content').html(response);
    //     },
    // });


  });
</script>

app/views/frontend/products/show.html.erb
<%
  scrubber = Loofah::Scrubber.new do |node|
    node.remove if node.name == 'script'
  end
%>
<div class="ui container" id="product_show">
  <div class="ui grid">
    <div class="nine wide computer nine wide tablet six wide mobile column">
      <div class="ui segment right floated">
        <%= image_tag @product.product_images.first.img_url, id: 'big-img', size: '500x500', "data-zoom-image": @product.product_images.first.img_url %>
        <div id="imgs-gallery">
          <% @product.product_images.each do |img| %>
            <a href="#" data-image="<%= img.img_url(:big) %>" data-zoom-image="<%= img.img_url %>">
              <%= image_tag img.img_url(:thumb), size: '70x70' %>
            </a>
          <% end %>
        </div>
      </div>
    </div>
    <div class="seven wide column">
      <div class="ui segment ">
        <div class="ui list">
          <%= form_tag add_to_frontend_cart_path, remote: true, id: 'select_variant_form', class: 'ui form' do %>
            <div class="item">
              <h2 class="ui header">
                <%= @product.title %>
              </h2>
              <h3 class="price_tag">
                  售价: ￥<span class="price_num"><%= @product.price %></span>
              </h3>
            </div>
            <% @options.each_with_index do |option, index_o| %>
              <div class="item">
                <div class="field option_field_box">
                  <label class="option_name"><%= option.name %> :</label>
                  <div class="ui left pointing red basic label" style="display:none">
                    请选择一个选项
                  </div>
                  <ul class="radio option option<%= index_o %>">
                    <% option.values.each_with_index do |val, index_v| %>
                      <li class="value">
                        <%= radio_button_tag "option#{index_o}", val, false, id: "option#{index_o}_v#{index_v}" %>
                        <label for='<%= "option#{index_o}_v#{index_v}" %>'><%= val %></label>
                      </li>
                    <% end %>
                  </ul>
                </div>
              </div>
            <% end %>

            <div class="item qty">
              <div class="inline field">
                <label>数量 :</label>
                <%= number_field_tag :quantity, 1, min: 1 %>
              </div>
            </div>

            <%= hidden_field_tag :variant_id %>

            <div class="item btns">
              <% if current_customer.present? %>
                <span class="wish_btn_wrapper"><%= render 'frontend/products/wish_btn' %></span>
                <%= button_tag class: 'ui yellow large button' do %>
                  <i class="shop icon"></i> 加入购物车
                <% end %>
              <% else %>
                <%= link_to frontend_sign_in_path(prev_location: request.url), class: 'ui yellow large button' do %>
                  <i class="star icon"></i> 收藏了再说
                <% end %>
                <%= link_to frontend_sign_in_path(prev_location: request.url), class: 'ui yellow large button' do %>
                  <i class="shop icon"></i> 加入购物车
                <% end %>
              <% end %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>

  <div class="ui segment">
    <h3 class="ui yellow dividing header">
      图文详情
    </h3>
    <div class="ui segment">
      <%= sanitize @product.body_html, scrubber: scrubber %>
    </div>
  </div>
</div>

<script>
  $(document).ready(function() {
    $('#select_variant_form').submit(function () {
      var valid = true;
      $.each($('.option'), function(index, val) {
        if ($(val).find('input:radio:checked').length == 0) {
          $(val).prev().show();
          valid = false;
        } else {
          $(val).prev().hide();
        }
      });
      if (!valid) {return false;}
    });

    $('#select_variant_form input:radio').on('click', function() {
      if ($('.option input:radio:checked').length == $('.option').length) {
        var arr = new Array();
        $(':radio:checked').each(function(){
          arr.push($(this).val());
        });
        $.ajax({
             type: 'GET',
             url: '/shop/variants/get_selected',
             dataType: 'script',
             data: { opts: arr, product_id: <%= @product.id %> }
         });
      }
    });
  });
</script>