config/routes.rb
Rails.application.routes.draw do
  namespace :backend, path: "admin" do
    root 'pages#home'

    get 'sign_in', to: 'sessions#new', as: 'sign_in'
    post 'sign_in', to: 'sessions#create'
    delete 'sign_out', to: 'sessions#destroy', as: 'sign_out'

    resources :users
    resources :categories, except: :show
    resources :custom_windows
    resources :products do
      member do
        get :set_cover
      end

      resources :options do
        collection do
          put :update_all
        end
      end
      resources :variants
      resources :product_images
    end

    resources :pictures, only: :create
  end

  namespace :frontend, path: "shop" do
    root 'pages#home'

    get 'sign_in', to: 'sessions#new', as: 'sign_in'
    post 'sign_in', to: 'sessions#create'
    delete 'sign_out', to: 'sessions#destroy', as: 'sign_out'

    get 'settings', to: 'customers#edit', as: :settings

    resources :search, only: :index

    get 'p/:slug', to: 'products#show', as: :display_spu
    resources :products, only: [:index], param: :slug do
      # get '/content', to: 'products#content'
      # get '/basic', to: 'products#basic'

      collection do
        get 'new_arrival'
        get 'hot_sales'
      end
    end

    resources :customers
    resources :addresses

    resources :variants do
      collection do
        get  :get_selected
      end
    end

    resource :cart, only: [:show] do
      post 'add_to_cart', to: 'carts#add', as: :add_to
      post 'remove_from_cart/:variant_id', to: 'carts#remove', as: :remove_from
      post 'change_qty/:variant_id', to: 'carts#change_qty', as: :change_qty_in
    end

    get 'my_wish_list', to: 'wish_lists#my', as: :my_wish_list
    post '/wish/:product_id', to: 'wish_lists#add', as: :add_to_wish_list
    delete '/wish/:product_id', to: 'wish_lists#remove', as: :remove_from_wish_list

    resources :categories, only: :show, param: :slug do
      get 'tags/:tag_id', action: :tag, on: :member, as: :tag
    end
    resources :tags, only: :show
  end

  root 'frontend/pages#home'
end

app/models/wish_list.rb
class WishList < ApplicationRecord
  belongs_to :wish_list_item, class_name: 'Product', foreign_key: 'product_id'
  belongs_to :customer
end

# == Schema Information
#
# Table name: wish_lists
#
#  id          :integer          not null, primary key
#  product_id  :integer
#  customer_id :integer
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#
# Indexes
#
#  index_wish_lists_on_customer_id  (customer_id)
#  index_wish_lists_on_product_id   (product_id)
#

app/controllers/frontend/addresses_controller.rb
class Frontend::AddressesController < Frontend::ApplicationController
  before_action :current_customer_exists?

  def index
    @addresses = current_customer.addresses
    @address   = Address.new
  end

  def create
    @address = current_customer.addresses.build(address_params)
    if @address.save
      flash[:notice] = '新建成功'
    else
      flash[:notice] = @address.errors.full_messages.join(' 。')
    end
    redirect_to frontend_addresses_url
  end

  def edit
    @addresses = current_customer.addresses
    @address   = current_customer.addresses.find(params[:id])
    render :index
  end

  def update
    @address = current_customer.addresses.find(params[:id])
    if @address.update(address_params)
      flash[:notice] = '已更新成功'
    else
      flash[:notice] = @address.errors.full_messages.join(' 。')
    end
    respond_to do |format|
      format.html { redirect_to frontend_addresses_url }
      format.js
    end
  end

  def destroy
    @address = current_customer.addresses.find(params[:id])
    @address.destroy
    redirect_to frontend_addresses_url
  end

  private

  def address_params
    params.require(:address).permit!
  end
end

app/controllers/frontend/application_controller.rb
class Frontend::ApplicationController < ActionController::Base
  layout "application"
  protect_from_forgery with: :exception
  before_action :detect_device_variant
  before_action :get_top_categories

  private

  def detect_device_variant
    request.variant = :phone if browser.device.mobile? || browser.device.tablet?
  end

  def current_customer
    if customer_id = session[:customer_id]
      @current_customer ||= Customer.find customer_id
    elsif customer_id = cookies.signed[:customer_id]
      customer = Customer.find customer_id
      if customer && customer.remember_token == cookies.signed[:remember_token]
        session[:customer_id] = customer.id
        @current_customer = customer
      end
    end
  end
  helper_method :current_customer

  def current_cart
    @current_cart ||= if current_customer
                        current_customer.cart_items
                      else
                        []
                      end
  end
  helper_method :current_cart

  def current_customer_exists?
    return unless current_customer.present?
    redirect_to frontend_root_path && return
  end

  def get_top_categories
    @categories = Category.get_categories
  end
end

app/controllers/frontend/carts_controller.rb
class Frontend::CartsController < Frontend::ApplicationController
  skip_before_action :get_top_categories, only: [:add, :remove, :change_qty]
  before_action :current_customer_exists?

  def show
    @cart_items = current_customer.cart_items
  end

  def add
    key = current_customer.cart_key
    variant_id = params[:variant_id]
    qty = params[:quantity]
    redis.hincrby key, variant_id, qty if variant_id.present?
  end

  def change_qty
    key = current_customer.cart_key
    variant_id = params[:variant_id]
    @variant = Variant.find variant_id
    qty = params[:quantity]
    redis.hset key, variant_id, qty if variant_id.present?
  end

  def remove
    redis.hdel current_customer.cart_key, params[:variant_id]
  end

  private

  def redis
    Redis.current
  end
end

app/controllers/frontend/categories_controller.rb
class Frontend::CategoriesController < Frontend::ApplicationController
  def show
    @category = Category.find_by(slug: params[:slug])
    @products = @category.products.not_deleted
                         .order('created_at DESC')
                         .page(params[:page]).per(2)

    render 'frontend/products/index'
  end

  def tag
    @tag = Tag.find(params[:tag_id])
    @category = Category.find_by(slug: params[:slug])
    @products = Product.tagged_with(@tag.name).not_deleted
                       .where(category: @category)
                       .order('created_at DESC')
                       .page(params[:page]).per(12)

    render 'frontend/products/index'
  end
end

app/controllers/frontend/customers_controller.rb
class Frontend::CustomersController < Frontend::ApplicationController
  def new
    @customer = Customer.new(customer_params)
  end

  def create
    @customer = Customer.new(customer_params)

    if @customer.save
      session[:customer_id] = @customer.id
      redirect_to root_path
    else
      flash[:notice] = @customer.errors.full_messages.join(' 。')
      redirect_to new_customer_path(customer: { name: customer_params[:name],
                                                email: customer_params[:email] })

    end
  end

  def edit

  end

  def update
    if current_customer && current_customer.authenticate(params[:customer][:old_password])
      if current_customer.update(customer_params)
        flash[:alert] = '密码更新成功, 请牢记, 谢谢.'
      else
        flash[:alert] = '确认密码不一致, 请重新输入.'
      end
    else
      flash[:alert] = '旧密码有误, 请重新输入'
    end
    redirect_to frontend_settings_path
  end

  private

  def customer_params
    params.require(:customer).permit(:email, :password, :password_confirmation, :name) if params[:customer]
  end
end

app/controllers/frontend/pages_controller.rb
class Frontend::PagesController < Frontend::ApplicationController
  def home
    # CustomWindow
    @cw0 = CustomWindow.features[0]
    @cw1 = CustomWindow.features[1]
    @cw2 = CustomWindow.features[2]
    @cw3 = CustomWindow.features[3]
    @cw4 = CustomWindow.features[4]
    @cw5 = CustomWindow.features[5]
    @cw6 = CustomWindow.features[6]
    # products list
    @products = Product.not_deleted.new_arrivals.page(params[:page]).per(12)
  end
end

app/controllers/frontend/products_controller.rb
class Frontend::ProductsController < Frontend::ApplicationController
  def index
    render :index
  end

  def new_arrival
    @products = Product.new_arrivals.page(params[:page]).per(12)
    index
  end

  def hot_sales
    @products = Product.hot_sales.page(params[:page]).per(12)
    index
  end

  def show
    @product = Product.where(slug: params[:slug]).first
    @options = @product.options
    @no_footer           = true
    @no_top_menu         = true
    @no_top_search       = true
    @display_bottom_menu = true
  end

  # def content
  #   @product = Product.where(slug: params[:product_slug]).first
  #   @p_body = @product.body_html
  # end
end

app/controllers/frontend/search_controller.rb
class Frontend::SearchController < Frontend::ApplicationController
  after_action -> { Suggestion.save_word(params[:q]) }, only: [:index]

  def index
    @search = Product.custom_search(params)
    @total  = @search.total_count
    @products = @search.results
  end
end

app/controllers/frontend/sessions_controller.rb
class Frontend::SessionsController < Frontend::ApplicationController
  def new
    if current_customer
      redirect_to frontend_root_path, notice: '已经登录了.'
      return
    end
  end

  def create
    customer = Customer.find_by(email: params[:email])

    if customer && customer.authenticate(params[:password])
      session[:customer_id] = customer.id

      if params[:remember_me].present?
        customer.remember
        cookies.signed[:customer_id] = { value: customer.id, expires: 1.week.from_now }
        cookies.signed[:remember_token] = { value: customer.remember_token, expires: 1.week.from_now }
      end

      redirect_to(params[:prev_url] || frontend_root_path)
    else
      redirect_to frontend_sign_in_path, alert: '邮箱与密码不匹配'
    end
  end

  def destroy
    session.delete(:customer_id)
    cookies.delete(:customer_id)
    cookies.delete(:remember_token)
    redirect_to frontend_root_path, notice: '帐户已登出'
  end
end

app/controllers/frontend/tags_controller.rb
class Frontend::TagsController < Frontend::ApplicationController
  def show
    @tag = Tag.find(params[:id])
    @products = Product.tagged_with(@tag.name).not_deleted
                       .order('created_at DESC')
                       .page(params[:page]).per(12)

    render 'frontend/products/index'
  end
end

app/controllers/frontend/variants_controller.rb
class Frontend::VariantsController < Frontend::ApplicationController

  def add_to_cart
  end

  def get_selected
    vals = params[:opts]
    product = Product.find params[:product_id]
    # options_count = product.options.count
    @variant = product.variants.where(option1: vals[0],
                                      option2: vals[1],
                                      option3: vals[2]).first
  end
end

app/controllers/frontend/wish_lists_controller.rb
class Frontend::WishListsController < Frontend::ApplicationController
  skip_before_action :get_top_categories, only: [:add, :remove]
  before_action :current_customer_exists?

  def my
    @wish_lists = current_customer.wish_lists
  end

  def add
    @product = Product.find(params[:product_id])
    current_customer.wish params[:product_id]
    @current_count = current_customer.wish_list_items_count
  end

  def remove
    @product = Product.find(params[:product_id])
    current_customer.wish params[:product_id]
    @current_count = current_customer.wish_list_items_count
  end
end

app/helpers/frontend/addresses_helper.rb
module Frontend::AddressesHelper
end

app/helpers/frontend/customers_helper.rb
module Frontend::CustomersHelper
end

app/helpers/frontend/products_helper.rb
module Frontend::ProductsHelper
end

app/helpers/frontend/search_helper.rb
module Frontend::SearchHelper
end

app/helpers/frontend/tags_helper.rb
module Frontend::TagsHelper
end

app/helpers/frontend/variants_helper.rb
module Frontend::VariantsHelper
  def get_cart_item_count(variant_id)
    Redis.current.hget(current_customer.cart_key, variant_id)
  end
end

app/views/frontend/wish_lists/add.js+phone.erb
$('.add-star').html("<%= j(render 'frontend/products/phone/wish_btn')%>");
$('.wish_count').transition('jiggle');
$('.star.icon').transition('jiggle');

app/views/frontend/wish_lists/add.js.erb
$('.wish_btn_wrapper').html("<%= j(render 'frontend/products/wish_btn')%>");
$('.wish_count').text(<%= @current_count %>);
$('.wish_count').transition('jiggle');
$('.star.icon').transition('jiggle');

app/views/frontend/wish_lists/my.html+phone.erb
<div id="my-wish-list">
  <div class="ui container">
    <h4 class="ui clearing horizontal divider header">
      #我的收藏#
    </h4>

    <% if @wish_lists.empty? %>
      <div class="ui disabled center aligned header">
        <i class="terminal icon"></i> 空空如也
      </div>
    <% else %>
      <div id="products-box">
        <div class="ui one cards">
          <% @wish_lists.includes(:wish_list_item).each do |wish| %>
            <div class="blue card wish<%= wish.product_id %>">
              <div class="image">
                <%= link_to frontend_remove_from_wish_list_path(wish.product_id), remote: true, method: :delete, data: {confirm: "确定取消收藏?"}, class: "ui right corner label" do %>
                    <i class="close icon"></i>
                <% end %>
              </div>
              <div class="content right-content">
                <%= link_to frontend_display_spu_path(wish.wish_list_item.slug) do %>
                    <%= image_tag(wish.wish_list_item.cover || 'logo.png', class: 'product-img') %>
                <% end %>
                <div class="header">
                  <%= link_to wish.wish_list_item.title, frontend_display_spu_path(wish.wish_list_item.slug) %>
                </div>
              </div>
              <div class="extra content">
            <span class="right floated">
              收藏于 <%= format_time wish.created_at %>
            </span>
            <span>
              ¥ <%= wish.wish_list_item.price %>
            </span>
              </div>
            </div>
          <% end %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/frontend/wish_lists/my.html.erb
<div class="ui container">
  <div class="ui segments">
    <div class="ui segment">
      <span class="ui yellow ribbon label">我的收藏</span>
    </div>
    <% if @wish_lists.empty? %>
        <div class="ui segment">
          <div class="ui disabled center aligned header">
            <i class="terminal icon"></i> 空空如也
          </div>
        </div>
    <% else %>
        <div class="ui segment">
          <div class="ui three stackable cards">
            <% @wish_lists.includes(:wish_list_item).each do |wish| %>
                <div class="card wish<%= wish.product_id %>">
                  <div class="image">
                    <%= link_to frontend_remove_from_wish_list_path(wish.product_id), remote: true, method: :delete, data: {confirm: "确定取消收藏?"}, class: "ui right corner label" do %>
                        <i class="close icon"></i>
                    <% end %>
                    <%= link_to frontend_display_spu_path(wish.wish_list_item.slug) do %>
                        <%= image_tag(wish.wish_list_item.cover || 'logo.png', style: 'width:100%') %>
                    <% end %>
                  </div>
                  <div class="content">
                    <div class="header">
                      <%= link_to wish.wish_list_item.title, frontend_display_spu_path(wish.wish_list_item.slug) %>
                    </div>
                  </div>
                  <div class="extra content">
                <span class="right floated">
                  收藏于 <%= format_time wish.created_at %>
                </span>
                <span>
                  <i class="user icon"></i>
                  ¥ <%= wish.wish_list_item.price %>
                </span>
                  </div>
                </div>
            <% end %>
          </div>
        </div>
    <% end %>
  </div>
</div>

app/views/frontend/wish_lists/remove.js.erb
$('.wish<%= params[:product_id]%>').remove();
$('.wish_count').text(<%= @current_count %>);
$('.wish_count').transition('jiggle');