config/routes.rb
Rails.application.routes.draw do
  namespace :backend, path: "admin" do
    root 'pages#home'

    get 'sign_in', to: 'sessions#new', as: 'sign_in'
    post 'sign_in', to: 'sessions#create'
    delete 'sign_out', to: 'sessions#destroy', as: 'sign_out'

    resources :users
    resources :categories, except: :show
    resources :custom_windows
    resources :products do
      member do
        get :set_cover
      end

      resources :options do
        collection do
          put :update_all
        end
      end
      resources :variants
      resources :product_images
    end

    resources :pictures, only: :create
  end

  namespace :frontend, path: "shop" do
    root 'pages#home'

    get 'sign_in', to: 'sessions#new', as: 'sign_in'
    post 'sign_in', to: 'sessions#create'
    delete 'sign_out', to: 'sessions#destroy', as: 'sign_out'

    get 'settings', to: 'customers#edit', as: :settings

    resources :search, only: :index

    get 'p/:slug', to: 'products#show', as: :display_spu
    resources :products, only: [:index], param: :slug do
      # get '/content', to: 'products#content'
      # get '/basic', to: 'products#basic'

      collection do
        get 'new_arrival'
        get 'hot_sales'
      end
    end

    resources :customers
    resources :addresses

    resources :variants do
      collection do
        get  :get_selected
      end
    end

    resource :cart, only: [:show] do
      post 'add_to_cart', to: 'carts#add', as: :add_to
      post 'remove_from_cart/:variant_id', to: 'carts#remove', as: :remove_from
      post 'change_qty/:variant_id', to: 'carts#change_qty', as: :change_qty_in
    end

    get 'my_wish_list', to: 'wish_lists#my', as: :my_wish_list
    post '/wish/:product_id', to: 'wish_lists#add', as: :add_to_wish_list
    delete '/wish/:product_id', to: 'wish_lists#remove', as: :remove_from_wish_list

    resources :categories, only: :show, param: :slug do
      get 'tags/:tag_id', action: :tag, on: :member, as: :tag
    end
    resources :tags, only: :show
  end

  root 'frontend/pages#home'
end

app/models/product.rb
class Product < ApplicationRecord
  include ProductsSearchable

  belongs_to :category
  has_many :variants, dependent: :destroy
  has_many :options, dependent: :destroy
  has_many :product_images, dependent: :destroy
  has_many :taggings, dependent: :destroy
  has_many :tags, through: :taggings, dependent: :destroy

  # accepts_nested_attributes_for :options

  validates_length_of :options, maximum: 3
  validates :title, presence: true
  validates :price, presence: true

  before_create :init_slug

  delegate :name, to: :category, prefix: true
  scope :not_deleted, -> { where(deleted_at: nil) }
  scope :hot_sales,
        -> { where(deleted_at: nil, hot_sale: 1).order('created_at DESC') }
  scope :new_arrivals,
        -> { where(deleted_at: nil, new_arrival: 1).order('created_at DESC') }

  SOLD_OUT = 0
  ON_OFFER = 1

  STATUS = {
    SOLD_OUT => '下架',
    ON_OFFER => '在售'
  }

  def tag_list=(names)
    self.tags = names.map do |n|
      Tag.where(name: n.strip).first_or_create!
    end
  end

  def tag_list
    tags.pluck(:name)
  end

  def self.tagged_with(name)
    Tag.find_by!(name: name).products
  end

  def wished_by_count_key
    "wished_by_count:#{id}"
  end

  private

  def init_slug
    loop do
      slug = SecureRandom.urlsafe_base64
      break self.slug = slug unless Product.exists?(slug: slug)
    end
  end
end

# == Schema Information
#
# Table name: products
#
#  id           :integer          not null, primary key
#  title        :string
#  body_html    :text
#  published_at :datetime
#  vendor       :string
#  keywords     :text
#  price        :decimal(8, 2)
#  category_id  :integer
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#  slug         :string
#  deleted_at   :datetime
#  stock_qty    :integer          default(0)
#  status       :integer          default(0)
#  hot_sale     :boolean          default(FALSE)
#  new_arrival  :boolean          default(TRUE)
#  cover        :string
#
# Indexes
#
#  index_products_on_category_id  (category_id)
#  index_products_on_deleted_at   (deleted_at)
#

app/controllers/backend/application_controller.rb
class Backend::ApplicationController < ActionController::Base
  include Pundit

  layout 'admin'
  protect_from_forgery with: :exception
  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized

  private

  def user_not_authorized(exception)
    flash[:alert] = '请先登录后再继续操作.'
    redirect_to(request.referrer || backend_root_path)
  end

  def current_user
    if user_id = session[:user_id]
      @current_user ||= User.find user_id
    elsif user_id = cookies.signed[:user_id]
      user = User.find user_id
      if user && user.remember_token == cookies.signed[:remember_token]
        session[:user_id] = user.id
        @current_user = user
      end
    end
  end
  helper_method :current_user

  def get_product(product_id = nil)
    product_id ||= params[:id]
    @product = Product.find product_id
  end
end

app/controllers/backend/categories_controller.rb
class Backend::CategoriesController < Backend::ApplicationController

  def index
    authorize Category
    @categories = Category.where(ancestry_depth: 0)
  end

  def new
    authorize Category
  end

  def create
    @category = Category.new(category_params)
    authorize @category
    if @category.save
      redirect_to backend_categories_url
    else
      flash[:notice] = @category.errors.full_messages.join(' 。')
      render :new
    end
  end

  def edit
    @category = Category.find(params[:id])
    authorize @category
  end

  def update
    @category = Category.find(params[:id])
    authorize @category
    if @category.update_attributes(category_params)
      redirect_to backend_categories_url
    else
      flash[:notice] = @category.errors.full_messages.join(' 。')
      render :edit
    end
  end

  def destroy
    @category = Category.find(params[:id])
    authorize @category
    if @category.present?
      @category.destroy
      @category.descendants.destroy_all
      redirect_to backend_categories_url
    end
  end

  private

  def category_params
    params.require(:category).permit!
  end
end

app/controllers/backend/custom_windows_controller.rb
class Backend::CustomWindowsController < Backend::ApplicationController
  before_action -> { authorize Product }

  def index
    @custom_windows = CustomWindow.order('position asc')
  end

  def new
    @custom_window = CustomWindow.new
  end

  def create
    @custom_window = CustomWindow.new custom_window_params

    if @custom_window.save
      redirect_to edit_backend_custom_window_path(@custom_window),
                  notice: '已成功创建'
    else
      render :new
    end
  end

  def edit
    @custom_window = CustomWindow.find params[:id]
  end

  def update
    @custom_window = CustomWindow.find params[:id]

    if @custom_window.update(custom_window_params)
      redirect_to edit_backend_custom_window_path, notice: '已更新'
    else
      render :new
    end
  end

  def destroy
    @custom_window = CustomWindow.find params[:id]
    @custom_window.destroy
    redirect_to backend_custom_windows_path
  end

  private

  def custom_window_params
    params.require(:custom_window).permit!
  end
end

app/controllers/backend/options_controller.rb
class Backend::OptionsController < Backend::ApplicationController
  before_action -> { get_product(params[:product_id]) },
                only: [:new, :create, :index, :edit, :update, :update_all]
  before_action -> { authorize Product }

  def new
    if @product.options.present?
      redirect_to backend_product_options_path(@product)
      return
    end
    @options = [@product.options.build]
  end

  def create
    @options = @product.options.build(options_params['options'])
    names = @options.map(&:name)

    if @options.all?(&:valid?) && names.uniq.length == names.length
      @options.each_with_index { |option, index| option.position = index + 1 }
      ActiveRecord::Base.transaction do
        @options.each(&:save)
      end
      VariantJob.perform_later(params[:product_id])
      redirect_to backend_product_options_path(@product),
                  notice: "已成功添加 #{@options.count} 个商品选项"
    else
      flash[:error] = '选项名称不能重复' if names.uniq.length != names.length
      render :new
    end
  end

  def index
    @options = @product.options
  end

  def edit
    @option = @product.options.find params[:id]
  end

  def update
    @option = @product.options.find params[:id]
    old_values = @option.values
    new_values = single_option_params['values']

    removed = old_values - new_values
    added   = new_values - old_values

    if @option.update(single_option_params)
      SingleOptionUpdateJob.perform_later(removed, added, @option.id)
      redirect_to edit_backend_product_option_path(@product, @option),
                  notice: "选项 #{@option.name} 已更新成功"
    else
      render :edit
    end
  end

  def update_all
    current_options = @product.options
    coming_options  = options_params['options']

    current_option_names      = current_options.map(&:name)
    coming_option_options     = coming_options.map { |option| option['name'] }

    deleted_options = current_option_names - coming_option_options
    fresh_options   = coming_option_options - current_option_names

    if deleted_options.present?
      current_options.where(name: deleted_options).destroy_all
      @product.options.reload.each_with_index { |option, index| option.position = index + 1 }
      @product.options.each(&:save)
    end

    if fresh_options.present?
      @product.options.reload
      options_to_add = coming_options.select { |option| option[:name].in?(fresh_options) }
      @options = @product.options.build(options_to_add)
      @product.options.each_with_index { |option, index| option.position = index + 1 }

      ActiveRecord::Base.transaction do
        @product.options.each(&:save)
      end
    end

    if deleted_options.present? || fresh_options.present?
      @product.variants.update_all(deleted_at: Time.now) # or destroy_all ?
      VariantJob.perform_later(params[:product_id])
    end

    # 不管新的是否符合全都 redirect
    redirect_to backend_product_options_path(@product),
                notice: '商品选项已更新'
  end

  private

  def options_params
    # params.require(:options).map(&:permit!)
    params.require(:options)
    params.permit(options: [:name, :position, values: []])
    # https://github.com/rails/strong_parameters/issues/140#issuecomment-21631515
  end

  def single_option_params
    params.require(:option).permit!
  end
end

app/controllers/backend/pages_controller.rb
class Backend::PagesController < Backend::ApplicationController
  def home
  end
end

app/controllers/backend/pictures_controller.rb
class Backend::PicturesController < Backend::ApplicationController
  def create
    @pic = Picture.new(pic: params['file'])
    respond_to do |format|
      if @pic.save
        format.html do
          render  json:  { name: params['file'].original_filename, href: @pic.pic.url, type: 'image' },
                  content_type: 'text/html',
                  layout: false
        end
      end
    end
  end
end

app/controllers/backend/product_images_controller.rb
class Backend::ProductImagesController < Backend::ApplicationController
  before_action -> { get_product(params[:product_id]) },
                only: [:index, :create, :destroy]
  before_action -> { authorize Product }

  def index
    @images = @product.product_images.order('position asc')
    @new_image = ProductImage.new
  end

  def create
    @image = @product.product_images.create(product_image_params)
  end

  def destroy
    @image = @product.product_images.find params[:id]
    @image.remove_img!
    @image.destroy
    redirect_to backend_product_product_images_path, notice: '图片已删除'
  end

  private

  def product_image_params
    params.require(:product_image).permit!
  end
end

app/controllers/backend/products_controller.rb
class Backend::ProductsController < Backend::ApplicationController
  before_action :get_product, only: [:show, :edit, :update, :destroy, :set_cover]
  before_action -> { authorize Product }
  def new
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to new_backend_product_option_path(@product), notice: '商品已创建成功' }
      else
        format.html { render :new }
        format.js { render :new }
      end
    end
  end

  def edit
  end

  def update
    if @product.update(product_params)
      redirect_to [:backend, @product]
    else
      render :edit
    end
  end

  def index
    @products = Product.not_deleted
  end

  def destroy
    @product.update(deleted_at: Time.now)
    redirect_to backend_products_path, notice: "#{@product.title} 已被删除"
  end

  def set_cover
    img = @product.product_images.find(params[:product_image_id])
    @product.update_column(:cover, img.img_url(:big))
  end

  private
  def product_params
    params.require(:product)
          .permit(:title, :price, :stock_qty, :status, :vendor, :body_html, :category_id, :new_arrival, :hot_sale, tag_list: [])
  end
end

app/controllers/backend/sessions_controller.rb
class Backend::SessionsController < Backend::ApplicationController
  def new
    if current_user
      redirect_to backend_root_path, notice: 'Already login.'
      return
    end
  end

  def create
    user = User.find_by(email: params[:email])

    if user && user.authenticate(params[:password])
      session[:user_id] = user.id

      if params[:remember_me].present?
        user.remember
        cookies.signed[:user_id] = { value: user.id, expires: 1.week.from_now }
        cookies.signed[:remember_token] = { value: user.remember_token, expires: 1.week.from_now }
      end

      redirect_to backend_root_path
    else
      redirect_to backend_sign_in_path, alert: '邮箱与密码不匹配'
    end
  end

  def destroy
    session.delete(:user_id)
    cookies.delete(:user_id)
    cookies.delete(:remember_token)
    redirect_to backend_root_path, notice: '帐户已登出'
  end
end

app/controllers/backend/users_controller.rb
class Backend::UsersController < Backend::ApplicationController
  def new
    @user = User.new(user_params)
  end

  def create
    # @user = User.new(user_params)

    # if @user.save
    #   session[:user_id] = @user.id
    #   redirect_to backend_root_path
    # else
    #   flash[:notice] = @user.errors.full_messages.join(' 。')
    #   redirect_to new_backend_user_path(user: {name: user_params[:name], email: user_params[:email]})
    # end
  end

  private

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation, :name) if params[:user]
  end
end

app/controllers/backend/variants_controller.rb
class Backend::VariantsController < Backend::ApplicationController
  before_action -> {get_product(params[:product_id])}, only: [:index, :edit, :update]
  before_action -> {authorize Product}

  def index
    @options  = @product.options
    @variants = @product.variants.not_deleted
  end

  def edit
    @options = @product.options
    @variant = @product.variants.find(params[:id])
  end

  def update
    @variant = @product.variants.find(params[:id])

    if @variant.update(variant_params)
      redirect_to backend_product_variants_path
    else
      @options = @product.options
      render :edit
    end
  end
  #
  # def new
  #   @product = Product.find(params[:product_id])
  #   @options = @product.options
  #   @variant = @product.variants.build
  # end
  #
  # def create
  #   @product = Product.find(params[:product_id])
  #   @variant  = @product.variants.build(variant_params)
  #   if @variant.save
  #     redirect_to backend_product_variants_path
  #   else
  #     @options = @product.options
  #     render :new
  #   end
  # end

  private

  def variant_params
    params.require(:variant).permit!
  end
end

app/controllers/frontend/products_controller.rb
class Frontend::ProductsController < Frontend::ApplicationController
  def index
    render :index
  end

  def new_arrival
    @products = Product.new_arrivals.page(params[:page]).per(12)
    index
  end

  def hot_sales
    @products = Product.hot_sales.page(params[:page]).per(12)
    index
  end

  def show
    @product = Product.where(slug: params[:slug]).first
    @options = @product.options
    @no_footer           = true
    @no_top_menu         = true
    @no_top_search       = true
    @display_bottom_menu = true
  end

  # def content
  #   @product = Product.where(slug: params[:product_slug]).first
  #   @p_body = @product.body_html
  # end
end

app/helpers/backend/categories_helper.rb
module Backend::CategoriesHelper
end

app/helpers/backend/custom_windows_helper.rb
module Backend::CustomWindowsHelper
end

app/helpers/backend/options_helper.rb
module Backend::OptionsHelper
end

app/helpers/backend/product_images_helper.rb
module Backend::ProductImagesHelper
  def highlight_default(product, image)
    if product.cover == image.img_url(:big)
      'yellow'
    end
  end
end

app/helpers/backend/products_helper.rb
module Backend::ProductsHelper
end

app/helpers/backend/variants_helper.rb
module Backend::VariantsHelper
end

app/helpers/frontend/products_helper.rb
module Frontend::ProductsHelper
end

app/views/backend/products/_form.html.erb
<%= form_for [:backend, product], html: {class: 'ui form'} do |f| %>
  <h4 class="ui dividing header">商品类目</h4>
  <div class="field">
    <label>类目名称</label>
    <%= f.select :category_id, options_from_collection_for_select(Category.all, 'id', 'name', params[:category_id] || product.category_id), { include_blank: true }, class: "ui fluid dropdown" %>
  </div>

  <h4 class="ui dividing header">基本信息</h4>
  <div class="field <%= 'error' if product.errors[:title].present? %>">
    <label>商品标题<%= " (#{@product.errors.messages[:title][0]})" if product.errors[:title].present? %></label>
    <div class="field">
      <%= f.text_field :title %>
    </div>
  </div>

  <div class="fields">
    <div class="three wide field <%= 'error' if product.errors[:price].present? %>">
      <label>价格<%= " (#{@product.errors.messages[:price][0]})" if product.errors[:price].present? %></label>
      <div class="field">
        <%= f.text_field :price %>
      </div>
    </div>
    <div class="seven wide field">
      <label>供应商</label>
      <div class="field">
        <%= f.text_field :vendor %>
      </div>
    </div>
    <div class="two wide field">
      <label>库存数量</label>
      <div class="field">
        <%= f.text_field :stock_qty %>
      </div>
    </div>
  </div>

  <div class="inline field inline-checkboxes">
    <div class="ui slider checkbox">
      <%= f.check_box :status %>
      <label>是否在售?</label>
    </div>
    <div class="ui slider checkbox">
      <%= f.check_box :new_arrival %>
      <label>新品上市?</label>
    </div>
    <div class="ui slider checkbox">
      <%= f.check_box :hot_sale %>
      <label>是否热销款?</label>
    </div>
  </div>

  <div class="twelve wide field">
    <div class="ui fluid multiple search selection dropdown">
      <%= select_tag "product[tag_list]", options_for_select(product.tag_list, product.tag_list), multiple: true  %>
      <div class="default text">请输入该商品的一些标签</div>
    </div>
  </div>

  <h4 class="ui dividing header">详细信息</h4>
  <div class="field">
    <label>描述主体</label>
    <div class="field">
      <%= f.text_area :body_html, class: 'trumbowyg-box' %>
    </div>
  </div>
  <%= f.submit "提交", class: "ui yellow button", disable_with: "提交中..." %>
<% end %>

app/views/backend/products/edit.html.erb
<div class="ui container" style="margin-top: 10px;">
  <div class="ui segments">
    <div class="ui clearing segment">
      <div class="ui large breadcrumb">
        <%= link_to 'Home', backend_root_path, class: 'section' %>
        <i class="right angle icon divider"></i>
        <div class="active section">编辑 SPU</div>
      </div>
      <div class="ui right floated image">
        <%= link_to backend_product_product_images_path(@product) do %>
          图片管理<i class="right angle icon divider"></i>
        <% end %>
      </div>
    </div>
    <div class="ui segment">
      <%= render 'form', product: @product %>
    </div>
  </div>
</div>

app/views/backend/products/index.html.erb
<div class="ui container">
  <div class="ui clearing segment">
    <h2 class="ui left floated header">
      <i class="table icon"></i> 所有商品(SPU)
    </h2>
    <h4 class="ui right floated header">
      <%= link_to new_backend_product_path, class: 'ui yellow header' do %>
        <i class="plus icon"></i> 创建新商品
      <% end %>
    </h4>
  </div>
  <table class="ui yellow table">
    <thead>
      <tr>
        <th>ID</th>
        <th>名称</th>
        <th>Slug</th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      <% @products.each do |product| %>
        <tr>
          <td><%= product.id %></td>
          <td><%= link_to product.title, backend_product_path(product) %></td>
          <td><%= product.slug %></td>
          <td>
            <div class="ui bulleted link list">
              <%= link_to edit_backend_product_path(product), class: 'item' do  %>
                <i class="edit icon"></i> 编辑
              <% end %>
              <%= link_to backend_product_variants_path(product_id: product.id), class: 'item' do  %>
                <i class="cubes icon"></i> 添加 SKU
              <% end %>
              <%= link_to backend_product_path(product), method: :delete, data: {confirm: '确定删除? 不可恢复!'}, class: 'item' do  %>
                <i class="minus icon"></i> 删除该商品
              <% end %>
            </div>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/backend/products/new.html.erb
<div class="ui container new_spu">
  <div class="ui large breadcrumb">
    <%= link_to 'Home', backend_root_path, class: 'section' %>
    <i class="right angle icon divider"></i>
    <div class="active section">新建 SPU</div>
  </div>

  <div class="ui two steps">
    <div class="active step">
      <i class="circle thin icon"></i>
      <div class="content">
        <div class="title">SPU INFO</div>
      </div>
    </div>
    <div class="disabled step">
      <i class="transgender icon"></i>
      <div class="content">
        <div class="title">SKU INFO</div>
      </div>
    </div>
  </div>

  <div class="ui segments">
    <div class="ui segment spu_form_box clearing">
      <%= render 'form', product: @product %>
    </div>
  </div>
</div>

app/views/backend/products/set_cover.js.erb
$('#p_img_<%= params[:product_image_id] %>').addClass('yellow');
$('.ui.left.corner').not('#p_img_<%= params[:product_image_id] %>').removeClass('yellow');

app/views/backend/products/show.html.erb
<div class="ui container" id="show_spu">
  <div class="ui large breadcrumb">
    <%= link_to 'Home', backend_root_path, class: 'section' %>
    <i class="right angle icon divider"></i>
    <div class="active section"><%= @product.title %></div>
  </div>

  <div class="ui clearing segment">
    <h2 class="ui header">
      <i class="cube icon"></i> <%= @product.title %>
    </h2>

    <div class="ui horizontal divided list right floated" style="margin-top: 0;">
      <div class="item">
        <div class="content">
          <div class="header">
            <%= link_to edit_backend_product_path(@product) do %>
              <i class="edit icon"></i>编辑当前 SPU
            <% end %>
          </div>
        </div>
      </div>
      <div class="item">
        <div class="content">
          <div class="header">
            <%= link_to backend_product_options_path(@product) do %>
                <i class="options icon"></i>编辑商品选项
            <% end %>
          </div>
        </div>
      </div>
      <div class="item">
        <div class="content">
          <div class="header">
            <%= link_to backend_product_variants_path(@product) do %>
                <i class="cubes icon"></i>SKU 列表
            <% end %>
          </div>
        </div>
      </div>
      <div class="item">
        <div class="content">
          <div class="header">
            <%= link_to backend_product_path(@product), method: :delete, data: {confirm: "确定删除?"} do %>
                <i class="red remove circle icon"></i>删除 SPU
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>

  <div class="">
    <table class="ui very basic collapsing celled table">
      <thead>
        <tr>
          <th></th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td>类目</td>
          <td><%= @product.category_name %></td>
        </tr>
        <tr>
          <td>状态</td>
          <td><%= Product::STATUS.fetch(@product.status) %></td>
        </tr>
        <tr>
          <td>价格</td>
          <td><%= @product.price %></td>
        </tr>
        <tr>
          <td>库存</td>
          <td><%= @product.stock_qty %></td>
        </tr>
        <tr>
          <td>供应商</td>
          <td><%= @product.vendor %></td>
        </tr>
      </tbody>
    </table>
  </div>
</div>