config/routes.rb
Rails.application.routes.draw do
  namespace :backend, path: "admin" do
    root 'pages#home'

    get 'sign_in', to: 'sessions#new', as: 'sign_in'
    post 'sign_in', to: 'sessions#create'
    delete 'sign_out', to: 'sessions#destroy', as: 'sign_out'

    resources :users
    resources :categories, except: :show
    resources :custom_windows
    resources :products do
      member do
        get :set_cover
      end

      resources :options do
        collection do
          put :update_all
        end
      end
      resources :variants
      resources :product_images
    end

    resources :pictures, only: :create
  end

  namespace :frontend, path: "shop" do
    root 'pages#home'

    get 'sign_in', to: 'sessions#new', as: 'sign_in'
    post 'sign_in', to: 'sessions#create'
    delete 'sign_out', to: 'sessions#destroy', as: 'sign_out'

    get 'settings', to: 'customers#edit', as: :settings

    resources :search, only: :index

    get 'p/:slug', to: 'products#show', as: :display_spu
    resources :products, only: [:index], param: :slug do
      # get '/content', to: 'products#content'
      # get '/basic', to: 'products#basic'

      collection do
        get 'new_arrival'
        get 'hot_sales'
      end
    end

    resources :customers
    resources :addresses

    resources :variants do
      collection do
        get  :get_selected
      end
    end

    resource :cart, only: [:show] do
      post 'add_to_cart', to: 'carts#add', as: :add_to
      post 'remove_from_cart/:variant_id', to: 'carts#remove', as: :remove_from
      post 'change_qty/:variant_id', to: 'carts#change_qty', as: :change_qty_in
    end

    get 'my_wish_list', to: 'wish_lists#my', as: :my_wish_list
    post '/wish/:product_id', to: 'wish_lists#add', as: :add_to_wish_list
    delete '/wish/:product_id', to: 'wish_lists#remove', as: :remove_from_wish_list

    resources :categories, only: :show, param: :slug do
      get 'tags/:tag_id', action: :tag, on: :member, as: :tag
    end
    resources :tags, only: :show
  end

  root 'frontend/pages#home'
end

app/controllers/frontend/addresses_controller.rb
class Frontend::AddressesController < Frontend::ApplicationController
  before_action :current_customer_exists?

  def index
    @addresses = current_customer.addresses
    @address   = Address.new
  end

  def create
    @address = current_customer.addresses.build(address_params)
    if @address.save
      flash[:notice] = '新建成功'
    else
      flash[:notice] = @address.errors.full_messages.join(' 。')
    end
    redirect_to frontend_addresses_url
  end

  def edit
    @addresses = current_customer.addresses
    @address   = current_customer.addresses.find(params[:id])
    render :index
  end

  def update
    @address = current_customer.addresses.find(params[:id])
    if @address.update(address_params)
      flash[:notice] = '已更新成功'
    else
      flash[:notice] = @address.errors.full_messages.join(' 。')
    end
    respond_to do |format|
      format.html { redirect_to frontend_addresses_url }
      format.js
    end
  end

  def destroy
    @address = current_customer.addresses.find(params[:id])
    @address.destroy
    redirect_to frontend_addresses_url
  end

  private

  def address_params
    params.require(:address).permit!
  end
end

app/controllers/frontend/application_controller.rb
class Frontend::ApplicationController < ActionController::Base
  layout "application"
  protect_from_forgery with: :exception
  before_action :detect_device_variant
  before_action :get_top_categories

  private

  def detect_device_variant
    request.variant = :phone if browser.device.mobile? || browser.device.tablet?
  end

  def current_customer
    if customer_id = session[:customer_id]
      @current_customer ||= Customer.find customer_id
    elsif customer_id = cookies.signed[:customer_id]
      customer = Customer.find customer_id
      if customer && customer.remember_token == cookies.signed[:remember_token]
        session[:customer_id] = customer.id
        @current_customer = customer
      end
    end
  end
  helper_method :current_customer

  def current_cart
    @current_cart ||= if current_customer
                        current_customer.cart_items
                      else
                        []
                      end
  end
  helper_method :current_cart

  def current_customer_exists?
    return unless current_customer.present?
    redirect_to frontend_root_path && return
  end

  def get_top_categories
    @categories = Category.get_categories
  end
end

app/controllers/frontend/carts_controller.rb
class Frontend::CartsController < Frontend::ApplicationController
  skip_before_action :get_top_categories, only: [:add, :remove, :change_qty]
  before_action :current_customer_exists?

  def show
    @cart_items = current_customer.cart_items
  end

  def add
    key = current_customer.cart_key
    variant_id = params[:variant_id]
    qty = params[:quantity]
    redis.hincrby key, variant_id, qty if variant_id.present?
  end

  def change_qty
    key = current_customer.cart_key
    variant_id = params[:variant_id]
    @variant = Variant.find variant_id
    qty = params[:quantity]
    redis.hset key, variant_id, qty if variant_id.present?
  end

  def remove
    redis.hdel current_customer.cart_key, params[:variant_id]
  end

  private

  def redis
    Redis.current
  end
end

app/controllers/frontend/categories_controller.rb
class Frontend::CategoriesController < Frontend::ApplicationController
  def show
    @category = Category.find_by(slug: params[:slug])
    @products = @category.products.not_deleted
                         .order('created_at DESC')
                         .page(params[:page]).per(2)

    render 'frontend/products/index'
  end

  def tag
    @tag = Tag.find(params[:tag_id])
    @category = Category.find_by(slug: params[:slug])
    @products = Product.tagged_with(@tag.name).not_deleted
                       .where(category: @category)
                       .order('created_at DESC')
                       .page(params[:page]).per(12)

    render 'frontend/products/index'
  end
end

app/controllers/frontend/customers_controller.rb
class Frontend::CustomersController < Frontend::ApplicationController
  def new
    @customer = Customer.new(customer_params)
  end

  def create
    @customer = Customer.new(customer_params)

    if @customer.save
      session[:customer_id] = @customer.id
      redirect_to root_path
    else
      flash[:notice] = @customer.errors.full_messages.join(' 。')
      redirect_to new_customer_path(customer: { name: customer_params[:name],
                                                email: customer_params[:email] })

    end
  end

  def edit

  end

  def update
    if current_customer && current_customer.authenticate(params[:customer][:old_password])
      if current_customer.update(customer_params)
        flash[:alert] = '密码更新成功, 请牢记, 谢谢.'
      else
        flash[:alert] = '确认密码不一致, 请重新输入.'
      end
    else
      flash[:alert] = '旧密码有误, 请重新输入'
    end
    redirect_to frontend_settings_path
  end

  private

  def customer_params
    params.require(:customer).permit(:email, :password, :password_confirmation, :name) if params[:customer]
  end
end

app/controllers/frontend/pages_controller.rb
class Frontend::PagesController < Frontend::ApplicationController
  def home
    # CustomWindow
    @cw0 = CustomWindow.features[0]
    @cw1 = CustomWindow.features[1]
    @cw2 = CustomWindow.features[2]
    @cw3 = CustomWindow.features[3]
    @cw4 = CustomWindow.features[4]
    @cw5 = CustomWindow.features[5]
    @cw6 = CustomWindow.features[6]
    # products list
    @products = Product.not_deleted.new_arrivals.page(params[:page]).per(12)
  end
end

app/controllers/frontend/products_controller.rb
class Frontend::ProductsController < Frontend::ApplicationController
  def index
    render :index
  end

  def new_arrival
    @products = Product.new_arrivals.page(params[:page]).per(12)
    index
  end

  def hot_sales
    @products = Product.hot_sales.page(params[:page]).per(12)
    index
  end

  def show
    @product = Product.where(slug: params[:slug]).first
    @options = @product.options
    @no_footer           = true
    @no_top_menu         = true
    @no_top_search       = true
    @display_bottom_menu = true
  end

  # def content
  #   @product = Product.where(slug: params[:product_slug]).first
  #   @p_body = @product.body_html
  # end
end

app/controllers/frontend/search_controller.rb
class Frontend::SearchController < Frontend::ApplicationController
  after_action -> { Suggestion.save_word(params[:q]) }, only: [:index]

  def index
    @search = Product.custom_search(params)
    @total  = @search.total_count
    @products = @search.results
  end
end

app/controllers/frontend/sessions_controller.rb
class Frontend::SessionsController < Frontend::ApplicationController
  def new
    if current_customer
      redirect_to frontend_root_path, notice: '已经登录了.'
      return
    end
  end

  def create
    customer = Customer.find_by(email: params[:email])

    if customer && customer.authenticate(params[:password])
      session[:customer_id] = customer.id

      if params[:remember_me].present?
        customer.remember
        cookies.signed[:customer_id] = { value: customer.id, expires: 1.week.from_now }
        cookies.signed[:remember_token] = { value: customer.remember_token, expires: 1.week.from_now }
      end

      redirect_to(params[:prev_url] || frontend_root_path)
    else
      redirect_to frontend_sign_in_path, alert: '邮箱与密码不匹配'
    end
  end

  def destroy
    session.delete(:customer_id)
    cookies.delete(:customer_id)
    cookies.delete(:remember_token)
    redirect_to frontend_root_path, notice: '帐户已登出'
  end
end

app/controllers/frontend/tags_controller.rb
class Frontend::TagsController < Frontend::ApplicationController
  def show
    @tag = Tag.find(params[:id])
    @products = Product.tagged_with(@tag.name).not_deleted
                       .order('created_at DESC')
                       .page(params[:page]).per(12)

    render 'frontend/products/index'
  end
end

app/controllers/frontend/variants_controller.rb
class Frontend::VariantsController < Frontend::ApplicationController

  def add_to_cart
  end

  def get_selected
    vals = params[:opts]
    product = Product.find params[:product_id]
    # options_count = product.options.count
    @variant = product.variants.where(option1: vals[0],
                                      option2: vals[1],
                                      option3: vals[2]).first
  end
end

app/controllers/frontend/wish_lists_controller.rb
class Frontend::WishListsController < Frontend::ApplicationController
  skip_before_action :get_top_categories, only: [:add, :remove]
  before_action :current_customer_exists?

  def my
    @wish_lists = current_customer.wish_lists
  end

  def add
    @product = Product.find(params[:product_id])
    current_customer.wish params[:product_id]
    @current_count = current_customer.wish_list_items_count
  end

  def remove
    @product = Product.find(params[:product_id])
    current_customer.wish params[:product_id]
    @current_count = current_customer.wish_list_items_count
  end
end

app/helpers/frontend/addresses_helper.rb
module Frontend::AddressesHelper
end

app/helpers/frontend/customers_helper.rb
module Frontend::CustomersHelper
end

app/helpers/frontend/products_helper.rb
module Frontend::ProductsHelper
end

app/helpers/frontend/search_helper.rb
module Frontend::SearchHelper
end

app/helpers/frontend/tags_helper.rb
module Frontend::TagsHelper
end

app/helpers/frontend/variants_helper.rb
module Frontend::VariantsHelper
  def get_cart_item_count(variant_id)
    Redis.current.hget(current_customer.cart_key, variant_id)
  end
end

app/views/frontend/common/_footer.html.erb
<div class="ui yellow vertical footer segment">
  <div class="ui center aligned container">
    <div class="ui stackable grid">
      <div class="three wide column">
        <h4 class="ui header">纯色系</h4>
        <div class="ui link list">
          <a class="item" href="#" target="_blank">关于我们</a>
          <a class="item" href="#" target="_blank">来信联系</a>
          <a class="item" href="#" target="_blank">诚聘英才</a>
          <a class="item" href="#" target="_blank">免责声明</a>
          <a class="item" href="#" target="_blank">法律声明</a>
          <a class="item" href="#" target="_blank">网站地图</a>
          <a class="item" href="#" target="_blank">FAQs</a>
        </div>
      </div>
      <div class="five wide column">
        <h4 class="ui header">合作伙伴</h4>
        <div class="ui link list">
          <a class="item" href="#" target="_blank">支付宝</a>
          <a class="item" href="#">微信支付</a>
          <a class="item" href="#">淘宝</a>
          <a class="item" href="#">Github</a>
        </div>
      </div>
      <div class="seven wide left floated column">
        <h4 class="ui yellow header">坐标</h4>
        <p> 广东省广州市番禺区</p>
        <h4 class="ui yellow header">技术支持</h4>
        <p>Ruby on Rails | Javascript | Elasticsearch | Redis | PostgreSQL | Semantic-UI</p>
      </div>
    </div>
    <div class="ui section divider"></div>
    <%= image_tag 'logo.png', class: "ui centered small image" %>
  </div>
</div>

app/views/frontend/common/_left_nav_categories.html.erb
<div class="item">
  <div class="header"><%= category.name %></div>
  <div class="menu">
    <% category.top_5_tags.each do |tag| %>
      <%= link_to "#{tag.name} (#{category.tag_products_count_map[tag.id.to_s].to_i})", tag_frontend_category_path(tag_id: tag.id, slug: category.slug), class: 'item' %>
    <% end %>
  </div>
</div>

app/views/frontend/common/_menu_cart_items_list.html.erb
<% current_cart.each do |variant| %>
  <div class="item"><%= variant.product.title %>
    <span class="ui yellow label"> <%= get_cart_item_count(variant.id) %> </span>
  </div>
<% end %>

app/views/frontend/common/_notice.html.erb
<% if notice %>
  <div class="ui yellow message">
    <div class="ui center aligned header">
      操作提示:
    </div>
    <ul class="list">
      <% notice.split(' 。').uniq.each do |sentence| %>
        <li><%= sentence %>.</li>
      <% end %>
    </ul>
  </div>
<% end %>
<% if alert %>
  <div class="ui yellow message">
    <div class="ui center aligned header">
      <%= alert %>
    </div>
  </div>
<% end %>

app/views/frontend/common/_secondary_menu.html.erb
<div class="ui secondary pointing menu">
  <div class="right menu">
    <%= form_tag frontend_search_index_path, method: :get, class: 'search_form item' do %>
      <div class="ui action input">
        <%= text_field_tag :q, params[:q], placeholder: '搜索' %>
        <%= button_tag type: 'submit', class: 'ui icon button search_btn' do  %>
          <i class="search icon"></i>
        <% end %>
      </div>
    <% end %>
    <%= link_to '新品', new_arrival_frontend_products_path, class: "#{active_page(new_arrival_frontend_products_path)} item" %>
    <%= link_to '爆款', hot_sales_frontend_products_path, class: "#{active_page(hot_sales_frontend_products_path)} item" %>
    <% @categories.each do |category| %>
      <%= link_to category.name, frontend_category_path(slug: category.slug), class: "#{active_page(frontend_category_path(slug: category.slug))} item" %>
    <% end %>
  </div>

</div>

app/views/frontend/common/_top_menu.html.erb
<div class="ui top menu" id="top_menu">
  <div class="item logo">
    <%= link_to root_path do %>
      <%= image_tag 'logo.png' %>
    <% end %>
  </div>
  <div class="right menu">
    <% if current_customer %>
      <div class="ui simple dropdown item" id="cart_dropdown">
        <%= link_to frontend_cart_path, class: 'item' do %>
          <i class="large shop icon" ></i> 我的购物车 <span class="cart_num floating ui yellow label"><%= current_customer ? current_customer.cart_items_count : 1 %></span>
        <% end %>
        <div class="menu">
          <div id="menu_cart_items_list">
            <%= render 'frontend/common/menu_cart_items_list' %>
          </div>
          <div class="divider"></div>
          <%= link_to frontend_cart_path, class: 'item checkout_link' do %>
            去购物车结算 <i class="chevron right icon"></i>
          <% end %>
        </div>
      </div>
    <% end %>
    <div class="item">
      <% wish_target = current_customer ? frontend_my_wish_list_path : frontend_sign_in_path(prev_location: frontend_my_wish_list_path) %>
      <%= link_to wish_target, class: 'item' do %>
        <i class="large star icon" ></i> 我的收藏夹 <span class="wish_count floating ui yellow label"><%= current_customer ? current_customer.wish_list_items_count : 1 %></span>
      <% end %>
    </div>
    <% if current_customer %>
      <div class="ui simple dropdown item">
        <%= current_customer.name %>
        <i class="dropdown icon"></i>
        <div class="menu">
          <%= link_to frontend_settings_path, class: 'item' do %>
            <i class="settings icon"></i> 个人设置
          <% end %>
          <%= link_to frontend_addresses_path, class: 'item' do %>
            <i class="street view icon"></i> 收货地址
          <% end %>
          <a class="item"><i class="database icon"></i> 订单历史</a>
          <%= link_to frontend_sign_out_path, method: :delete, class: 'item' do %>
            <i class="sign out icon"></i> 退出登录
          <% end %>
        </div>
      </div>
    <% else %>
      <%= link_to '注册', new_frontend_customer_path, class: "#{active_page(new_frontend_customer_path)} item"  %>
      <%= link_to '登录', frontend_sign_in_path, class: "#{active_page(frontend_sign_in_path)} item" %>
    <% end %>
  </div>
</div>